DFE-Digital/manage-free-school-projects

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProjectPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/validationComponent.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.sln
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Constants/ValidationConstants.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Demonstration/TagHelper.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Demonstration/TagHelper.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_ErrorSummary.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_TextInput.cshtml
added validation to the create project page
created a demonstration page for tag helpers
updated the automation
> added tag helpers to the create project page

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProjectPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/projectRow.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Index.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/wwwroot/package-lock.json
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/wwwroot/src/index.scss
fixed cypress tests based on page changes
> fixed styling issues on the homepage

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Dfe.ManageFreeSchoolProjects.API.Tests.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Factories/PagingResponseFactoryTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Tests/Authorization/AutomationHandlerTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Tests/Dfe.ManageFreeSchoolProjects.Tests.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Tests/Usings.cs
swapped to NSubstitute for mocking
https://www.reddit.com/r/dotnet/comments/15ljdcc/does_moq_in_its_latest_version_extract_and_send/
> removed moq as it has privacy concerns based on recent changes

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Helpers/DatabaseModelBuilder.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ApiTestsBase.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/DashboardApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/UserApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Controllers/DashboardController.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Controllers/UserController.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/StartupConfiguration/DependencyConfigurationExtensions.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Dashboard/GetDashboardByUserService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Users/CreateUserService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Entities/User.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Entities/UserProject.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Kpi.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/MfspContext.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20230811120139_AddKpiRidPrimaryKey.Designer.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20230811120139_AddKpiRidPrimaryKey.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20230811124232_UserProjectLinkTable.Designer.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20230811124232_UserProjectLinkTable.cs
added new table to link users and projects
added primary key to rid field on kpi
added integration test to test the get dashboard by user api
> table to link users and projects

- .github/workflows/continuous-integration-cypress.yml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/.eslintrc.json
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/plugins/generateZapReport.js
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/package-lock.json
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/package.json
- Adds a GitHub action that will run eslint over the CypressTests directory any time changes have been made. This will ensure code quality is kept high.
- Fixes outstanding errors in the generateZapReport file.
> Adds Cypress linting workflow, fixes existing lint errors

- .github/workflows/continuous-integration-dotnet.yml
Enables the scanner now the project has been set up in SonarCloud.
Results can be seen here: https://sonarcloud.io/project/overview?id=DFE-Digital_manage-free-schools-projects
**Note**: Will need the `SONAR_TOKEN` adding to the github secrets before being merged. This can be obtained from SonarCloud, or message me for the value.
> Enable sonarcloud scanning in dotnet build

- .github/workflows/build-and-push-image.yml
- This action will build a docker image, push it to Azure container registry, and then restart the Container on Azure
> Deployment workflow

- .github/workflows/build-and-push-image.yml
cypress will run every time commits are made to main 
slack reporter setup but needs an approved app and the webhook added to secrets
> added a cypress step to the pipeline

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/Tasklist-Dates.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesDetailsPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesSummaryPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/projectOverviewPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskList.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/support/commands.ts
Hey Sukhi,
Hoping I've made a decent start on this.  It'd be good to have your thoughts on this.
Many thanks
> 141586 dans auto dates

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/Tasklist-Dates.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesDetailsPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesSummaryPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/support/commands.ts
Hey Sukhi,  I believe I've fixed up these tests and added some stuff to check the validation for the latter academic year.  Cypress Tests seem to work.  Hopefully they're ready to merge into your date-tasks branch on Dev.
Cheers
> Refixing dans dates auto

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/Tasklist-Dates.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesDetailsPage.ts
Hey Sukhi,
Have put in a Start academic year potato/invalid date format test like you suggested.
Many thanks
> Start academic year potato test

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/SearchTrustTask.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/ViewTrustTask.cshtml.cs
and corrected regex validation for search trust page
> Fixed school name not loading on view trust page 

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/appsettings.json
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/appsettings.json
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
This PR will allow us to deploy a secured Blob Storage Container on Azure.
The web container app will automatically be given an authenticated URL to access the storage container via an environment variable "ConnectionStrings__BlobStorage"
> Deploy blob storage

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/SchoolType.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/ProjectMapper.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/TasksMapper.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/SchoolType.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/School/EditSchoolTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/School/EditSchoolTask.cshtml.cs
> Now display FurtherEducation school type if currently set/legacy school

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-risk.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/risk/projectRiskSummaryPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/RiskRatingLabelBuilder.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/RiskSummary.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/wwwroot/src/css/risk.scss
if a risk rating is in the past, the title says past ratings 
if a risk rating is in the past do not show the update risk button 
added css for amber tag
> 143928: risk rating content pages

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/Tasklist-Dates.cy.ts
Attempting to fix broken dates test
> Attempting to fix lines 66-73 inclusive

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Dashboard/_Dashboard.cshtml
> Remove project managed by filter form your projects tab

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectByTaskApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/StartupConfiguration/DependencyConfigurationExtensions.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Constituency/UpdateConstituencyTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Dates/UpdateDatesTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/IUpdateTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/RegionAndLocalAuthority/UpdateRegionAndLocalAuthorityTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/RiskAppraisalMeeting/UpdateRiskAppraisalMeetingTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/School/UpdateSchoolTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Trusts/UpdateTrustTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/UpdateProjectByTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/UpdateTaskServiceParameters.cs
makes it easier to work on tasks in parallel without having to work in the same files
> refactored update task into separate files

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Public/CookiePreferences.cshtml
cookies page content reworded as in the prototype, back to projects button added also
changes to cookie page only page only
no tests 
content based on https://free-schools-store-prototype.herokuapp.com/beta-sprint-9/cookies
> cookies page content reworded

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_CookieBanner.cshtml
reject option added to cookie banner
wording updated to match user story wording
> reject cookies added to cookie banner

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProject/createProjectPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/task-summary-base.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/AgeRange.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/Capacity.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/CheckYourAnswers.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/CheckYourAnswers.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ClassType.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ConfirmTrustTask.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/Confirmation.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/Confirmation.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/CreateProjectBaseModel.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/FaithStatus.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/FaithType.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/FormsOfEntry.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/LocalAuthority.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/NotifyUser.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ProjectId.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ProvisionalOpeningDate.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/Region.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/School.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/SchoolPhase.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/SchoolType.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/SearchTrust.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Services/CookieCache.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Services/Project/CreateProjectCache.cs
Updated create project journey automation and some navigation fixes
> Finished create project journey

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Models/Links.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Public/CookiePreferences.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Public/Cookies.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Public/Cookies.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_CookieBanner.cshtml
minor fixes to cookies banner and cookies page
cookies page renamed
> Fix banner and cookiepage bugs

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RiskAppraisalMeeting/ViewRiskAppraisalMeetingTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RiskAppraisalMeeting/ViewRiskAppraisalMeetingTask.cshtml.cs
this shows a risk rating and summary with a link to the risk summary page
> link from task appraisal added

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddEducationRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddFinanceRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddGovernanceAndSuitabilityRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddOverallRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/RiskSummary.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/_RiskForm.cshtml
further bug fixes for risk ratings
> bug fixes to risk ratings

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/TrustTask.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectByTaskApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Project/ProjectMapperTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/EnumParsers.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/ProjectMapper.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/GetTrustByRefService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/SearchTrustByRefService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Trusts/GetTrustTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ConfirmTrustTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ConfirmTrustTask.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/EditTrustTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/EditTrustTask.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/ViewTrustTask.cshtml
trust enums added
front end updated
api unit tests updated
> Trust type enums added

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/confirmTrustPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProject/createProjectPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/ConfirmTrustTask.cshtml
cypress tests updated 
create project page assertions added
confirm trust task page changes to allow values to render correctly in cypress test
> cypress tests updated

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddEducationRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddFinanceRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddGovernanceAndSuitabilityRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddOverallRisk.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddRiskAppraisalForm.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddRiskConfirmation.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddRiskReview.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/_RiskForm.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Constituency/SearchConstituency.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RegionAndLA/EditLocalAuthority.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RegionAndLA/EditRegion.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RegionAndLA/ViewRegionAndLocalAuthority.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/EditTrustTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Trust/SearchTrustTask.cshtml
updated the titles of the following:
risk pages
region and trust tasks
> 153159: updated the page titles to follow convention

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Helpers/DatabaseModelBuilder.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ContactsApiTests.cs
> contacts integration tests

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-risk.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Tests/Utils/StringChunkerTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Services/CookieCache.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Utils/StringChunker.cs
When cookie size increases, splits cookies into multiple cookies
> Split cookies based on size

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/tasklist-kick-off-meeting.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskListPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-kick-off-meeting.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Constants/ValidationConstants.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/KickOffMeeting/EditKickOffMeetingTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/KickOffMeeting/EditKickOffMeetingTask.cshtml.cs
cypress tests for kick off meeting
> cypress tests for kick off meeting

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/ArticlesOfAssociation/ViewArticlesOfAssociationTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/KickOffMeeting/ViewKickOffMeetingTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/TagHelpers/SummaryItemTagHelper.cs
Also fixed link on Articles of Association and Kick off meeting sharepoint links
> Added option to render as link on summary page

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Contacts/EditTrustChairContactPage.cshtml
ally bug fix on edit trust chair
> ally fix for trust chair

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/ProjectOverviewResponse.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectOverviewApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/ProjectOverview/GetProjectOverviewService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-overview.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/ProjectOverview.cshtml
trust types to show correct information
tests updated
> amend trust types

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_Layout.cshtml
> element moved

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/DraftGovernancePlanTask.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/GetProjectByTaskResponse.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/ProjectByTaskSummaryResponse.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/TaskName.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/UpdateProjectByTaskRequest.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/GetProjectByTaskSummaryApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/Tasks/DraftGovernancePlanTaskApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/Tasks/TaskExtensions.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Project/DraftGovernancePlan/GetDraftGovernancePlanTaskSummaryServiceTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Controllers/ProjectTaskController.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/StartupConfiguration/DependencyConfigurationExtensions.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/DraftGovernancePlan/GetDraftGovernancePlanService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/DraftGovernancePlan/GetDraftGovernancePlanTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/DraftGovernancePlan/GetDraftGovernancePlanTaskSummaryService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/DraftGovernancePlan/UpdateDraftGovernancePlanService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/DraftGovernancePlan/UpdateDraftGovernancePlanTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/FinancePlan/GetFinancePlanTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/GetProjectByTaskService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/draft-governance-plan.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/finance-plan.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskListPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/editDraftGovernancePlanPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Constants/RouteConstants.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/DraftGovernancePlan/EditDraftGovernancePlan.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/DraftGovernancePlan/EditDraftGovernancePlan.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/DraftGovernancePlan/ViewDraftGovernancePlan.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/DraftGovernancePlan/ViewDraftGovernancePlan.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/TaskList.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/ViewTaskBaseModel.cs
created an api for updating a draft governance plan
changed architecture of the api test so that it is more modular 
we always get merge conflicts when working on the same area
> 147088: task for updating governance plans

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-Dates.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/datesDetailsPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Dates/EditDatesTask.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Dates/EditDatesTask.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/Dates/ViewDatesTask.cshtml
rewrote the dates task test to make it simpler
> 153969: removed opening academic year

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-risk.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/risk/editProjectRiskPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Configuration/Existing/RagConfiguration.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240222104437_RafSharePointLinkFieldLength500.Designer.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240222104437_RafSharePointLinkFieldLength500.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddRiskAppraisalForm.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Risk/AddRiskAppraisalForm.cshtml.cs
added validation to the RAF sharepoint link to ensure it is a URL and less than 500 characters
> 157019: added validation to the raf sharepoint link

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Dfe.ManageFreeSchoolProjects.API.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Startup.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/appsettings.json
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Program.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Startup.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/appsettings.json
Standardising our logging to use app insights, like other applications do. Removed the existing logging to sentry
> 157358: added app insights logging

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/LocalAuthority.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RegionAndLA/EditLocalAuthority.cshtml.cs
local authorities to sort alphabetically
> sort added to alphabetically

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Reports/ProjectReportBuilderTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/EducationBrief/EducationBriefTaskBuilder.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Reports/AllProjectsReportService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Reports/ProjectReportBuilder.cs
> education brief reports

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Reports/SfaReportBuilderTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Reports/SfaReportBuilder.cs
The following issues where found when running with the dev data:
removed commas from school name as it broke the csv export 
parse amounts as doubles, so that the value is not set incorrectly when doing comparisons
> 158996: fixed data issues with sfa export

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Sites/ProjectSite.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Helpers/AssertionHelper.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectOverviewApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectSiteApiTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Sites/GetProjectSitesService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Sites/UpdateProjectSiteService.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-sites.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/siteInformation/editSiteInformationPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/siteInformation/viewSiteInformationPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Entities/Property.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240322115545_AddPropertyDatePlanningPermissionObtained.Designer.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240322115545_AddPropertyDatePlanningPermissionObtained.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/SiteInformation/EditSiteInformation.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/SiteInformation/EditSiteInformation.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/SiteInformation/_SiteDetails.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/TagHelpers/DateInputTagHelper.cs
fixed back link
added site type to edit page headers
added field date planning permission obtained
added field start date of site occupation
> 157319: added date fields to site information

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/support/commands.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/support/e2e.ts
Added custom invoke function for nicer syntax in spec files
Added this function to the Chainable interface in e2e.ts
Fingers crossed this all fits ok with GPP
(Only called this custom function within the enterDate() function in commands.ts for now)
> Auto add custom invoke

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/constituencySearchPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/dateComponent.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/homePage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/risk-appraisal-meeting-page.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/schoolDetailsPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/Getting-ready-to-open/edit-accepted-offers-evidence-cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/Getting-ready-to-open/edit-applications-evidence-cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-admissions-arrangements.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-articles-of-association.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-kick-off-meeting.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-model-funding-agreement.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-statutory-consultation.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/editDraftGovernancePlanPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/editFinancePlanPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/project-development-grant/edit-payment-schedule.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/project-development-grant/edit-refunds.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/project-development-grant/edit-stop-payments.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/project-development-grant/edit-trust-letter.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/project-development-grant/edit-write-off.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/trustDetailsPage.ts
Updated all .clear().type() function calls to call custom .typeFast()
> Auto update all type calls to type fast

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Configuration/Existing/PoConfiguration.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240416123117_IncreasePupilNumbersFieldSizes.Designer.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240416123117_IncreasePupilNumbersFieldSizes.cs
ensure that all fields can accept a total of 9999
> 162961: increase the field size on pupil numbers

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/project-development-grant/payment-schedule.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/project-development-grant/trust-letter-sent.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/PDG/EditPDGTrustGrantLetter.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/PDG/EditPDGTrustGrantLetter.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/PDG/ViewPDG.cshtml
- release-notes.md
Release notes for Candidate 0.3.0 (Sprint 17 & Sprint 18 Release A)
Updated release notes to include Jack's financial plan updated field mappings
Looking to merge this into release/0-3-0 for Sukhy
> Auto release candidate0.3 notes

- release-notes.md
Sorry, removed @Jacks Finance plan fields stuff from the release notes...
> removed Finance plan fields mapping story from release-notes

- Dockerfile.api
- Dockerfile.web
This will be displayed in GitHub and will help distinguish between the Web App and the API packages
> Added docker image description

- terraform/README.md
- terraform/variables.tf
The image tag used in the release pipeline is 'latest' not 'web-latest'
> Set the default image tag to 'latest'

- release-notes.md
Please let me know if you want me to trim some of the froth...
> Added release candidate 0.5.0 notes to release-notes.md

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- release-notes.md
Fixes filter test where assertion was expecting 1 project to come back when 20 are actually returned...
> Auto fix homepage test

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- release-notes.md
Reverts DFE-Digital/manage-free-school-projects#597
> Revert "Auto fix homepage test"

- .github/workflows/build-and-push-image.yml
- release-notes.md
Most likely last release for MFSP public beta.
> Release 0.7.0 release notes

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
- Allow us to set the SKU of the SQL server using Terraform
> Set the SKU of SQL Server

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Dfe.ManageFreeSchoolProjects.API.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Startup.cs
The API must have a default deny CSP configured and some sensible HTTP Headers set
> [API] Set minimum security headers for all requests

- terraform/README.md
- terraform/data-protection.tf
* Sets an expiry date on Key Vault Keys
* Enables Diagnostic Audit Logs for Key Vault
> Update Data Protection module to v1.1.0

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- Contains dependency updates, azure configuration tweaks, and rate limit policy adjustments
> Update to v1.8.3 of the Container App Module

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-School.cy.ts
This PR covers - Updating cypress test for task list summary check for Residential or Boarding option
> Update cypress test for summary check

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/Getting-ready-to-open/impact-assessment.cy.ts
This PR updated the test as per the new changes for Impact assessment.
The changes will fix  one of the test failing in the cypress test suite however there is one more test related to Tasklist-Dates which is failing, but it's not related to this ticket
> Updated text as per the new changes for Impact assessment

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/Getting-ready-to-open/impact-assessment.cy.ts
Missed pushing all the changes for the impact assessment in previous PR thus the test still failed.
> Fix impact assessment

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/cookie-consent.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/footerLinks.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/smoke/smoke-create-individual-project-to-check-answers-page.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/task-summary-base.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/support/commands.ts
Covered footer links and cookies page along with the Create project button.
> Coved few more scenarios 

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-Dates.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/projectRow.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/projectTable.ts
This PR covers some more scenarios for validation - age range, date and also includes to View the project from project list page.
> Covered some more scenarios

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/governance-plan-central.cy.ts
This PR fixes the cypress test for Governance plan for central route
> Fix governance plan for central

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-Dates.cy.ts
> Fix task-list dates test

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/api/domain.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-central-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-presumption-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-overview.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProject/createProjectPage.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/homePage.ts
Fixed cypress test failed due to new changes. This PR also adds the Central route project flow
> Fix cypress test failed due to new changes

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-central-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-presumption-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-overview.cy.ts
Fixed failed cypress test which were failing due to  recent changes in the MFSP app
> Fix cypress test 

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-central-project.cy.ts
> Updated central route project

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Tests/Project/BulkEditFileValidatorTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/BulkEdit/BulkEditComplete.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/BulkEdit/BulkEditFileUpload.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/BulkEdit/BulkEditFileUpload.cshtml.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Services/BulkEdit/BulkEditFileValidator.cs
Changed upload tab to enter data tab
Fixed typo on invalid header message
Fixed the upload showing on check your answers
Fixed pluralization of confirmation message
> Various fixes for bulk edit

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/smoke/smoke-create-central-project-to-check-answers-page.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/smoke/smoke-create-presumption-project-to-check-answers-page.cy.ts
> Updated smoke test for Test env

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-presumption-project.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/tasklist-education-brief.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskListPage.ts
Few of the cypress test are failing due to the recent changes done in the project. This PR fixes those.
> Fix cypress test

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/homePage.ts
Skips filter tests in regard to filtering by project status and the filter caches.
> Test skip filter tests

- release-notes.md
Added release notes for release 19 release candidate
> Added release notes for release 19

- release-notes.md
This release includes following tickets : 
182430 - Build: Finance Plan changes - Supporting Underwriting Agreements
200711 - Front End: Bug fix for null references and label changes on Pupil Numbers page
> MFSP release 1.0.0

- release-notes.md
Release notes updated for release1.0.1 which includes the changes 
200388: Add new data to MFSP all projects download
> MFSP: Release1.0.1

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/SchoolType.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Project/ProjectMapperTests.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/ProjectMapper.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-School.cy.ts
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/ProjectConstants.cs
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/School/EditSchoolTask.cshtml
Added a new school type, Voluntary Aided. 
This affects the School Task and the Create journey
This will have "Specialist Resource Provisions" which means that it will work similar to Mainstream schools
> Added voluntary aided option to school type

- .dockerignore
- Dfe.ManageFreeSchoolProjects/.dockerignore
- Dockerfile.api
- Dockerfile.web
* Removing " chars from the FROM statements means renovate can now read the urls
* Updated dockerignore
* Split out csproj restore steps for better caching
* Consolidated `RUN` commands
> Improve layer management in Dockerfile

- .github/workflows/continuous-integration-dotnet.yml
* This workflow will become a required gate so must run on all files
> Remove path filters

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Dashboard/_Dashboard.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/ImpactAssessment/ViewImpactAssessmentTask.cshtml
Tickets:
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/182834
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/177869
> Section 9 letter guidance and projects list text not resizing properly

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Dashboard/_Dashboard.cshtml
> Projects table row text zoom

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Startup.cs
* Fixes issues with trying to run the app on a local machine that does not have /srv/app/storage path
> Do not use fixed filesystem for data protection

- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.csproj
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_Layout.cshtml
- Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Program.cs
Ticket: https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/223852
Now we have App Insight data flowing from FE.
Also with the page names
> App Insights not showing page title in MFSP
