DFE-Digital/manage-free-school-projects

.github/workflows/continuous-integration-dotnet.yml
The .NET build test should run on any environment and not be limited to 'development'
=> Removed invalid 'dev' environment

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/appsettings.json
The previous DSN was for the Prepare Transfers service. This new DSN is specific to MFSP.
=> Update Sentry DSN

terraform/README.md, terraform/container-apps-hosting.tf, terraform/locals.tf, terraform/variables.tf
**What does this change do?**
- disables the container app monitor for the time being
- switch to using http health check for front door
- use branched version of the container app module so we can test refactored code
**Why do we need it?**
- Currently the container app liveness probe fails and the container crashes, this is a false positive so for the time being I am switching off the monitor until there is a working health check endpoint
- https requests are also failing to be responded to by the container but switching to http works
- Using the branched version of the module allows us to leverage the new refactored terraform code in the latest major version of the module which is currently unreleased but being tested (by this app!)
=> Use new container app module

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectByTaskApiTests.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Controllers/ProjectTaskController.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/GetProjectByTaskService.cs
changed inner joins to left outer joins for get project by task so the project is still returned
handle when project cannot be found by returning a 404
=> fixed issue where tasks would not load without dependent data

.github/workflows/build-and-push-image.yml
- The azure container app revision update task uses the correct image tag
- The image tag has been updated to reflect the changes in [this commit](https://github.com/DFE-Digital/manage-free-schools-projects/pull/141/commits/97b4d3605d3fb9ec3f72853ae6b5feb2c5039fc2)
- The task now uses matrix to concurrently update both the web and api containers at the same time
- This is a fix for [failing deployments](https://github.com/DFE-Digital/manage-free-schools-projects/actions/runs/6156618108/job/16705852814)
=> Update the API container revision on push

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskListPage.ts
Fixes the Tasklist-Region and LA script by incrementing the index/subscript for the "completed" status check on the tasklist page
Added a .skip to the latter describe-block in the create-individual-project.cy.ts spec file
=> Fix tasklist region and la skip create single project

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress.config.ts
Adds a User-Agent header to Cypress' config to mitigate Azure's bot traffic rules
=> Add Cypress User-agent to config

terraform/README.md, terraform/container-apps-hosting.tf, terraform/locals.tf, terraform/variables.tf
In the Container App definition, switch from using admin access keys, to using user assigned managed identity with the `acrpull` permission when authenticating with Azure Container Registry to pull the latest image
=> deploy user assigned managed identity

.github/workflows/build-and-push-image.yml, .github/workflows/continuous-integration-dotnet.yml
Updates the github actions versions we use to be ones that support node 20 now that node 16 is being deprecated.
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update workflows to use actions on node 20

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Contracts/Project/Tasks/DatesTask.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectByTaskApiTests.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Dates/GetDatesTaskService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/Dates/UpdateDatesTaskService.cs
Since our APIs do not allow partial updating, if we leave the field in, it will get set to null when we update the dates task. Even though the opening academic year field is not visible
Originally it was left in, just in case we changed our minds later, but the impact will change data, which we do not want
=> 156809: removed opening academic year from api

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/draft-governance-plan.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/tasklist-articles-of-association.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/pre-opening/tasklist-kick-off-meeting.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-articles-of-association.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/edit-kick-off-meeting.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/tasks/pre-opening/editDraftGovernancePlanPage.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Configuration/Existing/MilestonesConfiguration.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240219115756_IncreaseSharePointFieldsTo500.Designer.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240219115756_IncreaseSharePointFieldsTo500.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Constants/ValidationConstants.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/ArticlesOfAssociation/EditArticlesOfAssociationTask.cshtml.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/DraftGovernancePlan/EditDraftGovernancePlan.cshtml.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/KickOffMeeting/EditKickOffMeetingTask.cshtml.cs
Link fields are typically bigger than 100 characters, this change increases the limit of all link fields in the database to 500. all fields have been changed so that future tasks don't end up using the 100 limit, which is what the field limit is from the database we imported from KIM originally
=> 156799: increase the size of link fields to 500

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Controllers/ProjectTaskController.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/Tasks/UpdateProjectByTaskService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Tasks/CreateTasksService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Tasks/GetAllTasksStatusService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Tasks/GetTaskStatusService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Tasks/UpdateTaskStatusService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Create/Individual/LocalAuthority.cshtml.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Project/Tasks/RegionAndLA/EditLocalAuthority.cshtml.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Services/ErrorService.cs
single or default will throw an error if more than one record is found, we should use our gateways to make sure the data is correct, rather than throwing errors in a random part of the code
the bug that has been fixed was duplicated project ids, which are validated by the client journey
=> 157217: changed all single or default to first or default

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Helpers/DatabaseModelBuilder.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/AuditTests.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectApiTests.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API.Tests/Integration/ProjectRiskApiTests.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/UseCases/Project/CreateProjectService.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/api/requestBuilder.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/Getting-ready-to-open/applications-evidence.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-School.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/schoolDetailsPage.ts
set the wave when creating projects in cypress
check that alternative provision and special needs are not shown if school is special
=> fix cypress tests that failed on 08-04-24

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Configuration/Existing/PoConfiguration.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240416090252_IncreasePupilNumbersPre16CapacityFieldLength.Designer.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.Data/Migrations/20240416090252_IncreasePupilNumbersPre16CapacityFieldLength.cs
this field is a total of two fields that have a maximum of 9999, therefore the original size 4, was never going to be enough
Since it is a total field, I have changed it to 100, to be consistent with the other totals fields on the table
=> 162855: increased field length of YR-Y11 (pre-16) capacity

.github/workflows/build-and-push-image.yml
* switching to the reusable workflow ensures the release process is aligned to the other services within RSD
* this workflow is invoked using a matrix strategy which means it will build the api and app separately and they will be tagged as separate packages `"mfsp-app"` and `"mfsp-api"` whereas before they were both `"mfsp-app"` just with a different tag prefix of `"app-<release>"` or `"api-<release>"`. 
Having them as separate packages makes more sense because they are separate microservices
=> Use a reusable GitHub Workflow

.github/workflows/build-and-push-image.yml
Waiting for https://github.com/DFE-Digital/deploy-azure-container-apps-action/pull/11
setting a tag prefix allows us to differentiate between the web app and the api docker images
=> Docker build tag prefix

.github/workflows/build-and-push-image.yml, .github/workflows/cypress-tests.yml
**What is the change?**
Moves the Cypress tests into their own workflow, which is triggered after a deploy and can be triggered manually for dev/staging
**What is the impact?**
There should be no noticeable change for users in terms of process for deployments. New capability to trigger manually.
**Azure DevOps Ticket**
[#165644](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/165644)
=> Move Cypress tests into reusable workflow

terraform/.terraform.lock.hcl, terraform/README.md, terraform/providers.tf, terraform/versions.tf
By setting this value to true we can ensure any data sources used by the Container App module are correctly handled as HCL syntax instead of JSON.
JSON output was previously used in earlier versions of the AzAPI provider but they have since switched to using HCL which will eventually become the default instead of JSON.
=> Ensure data sources always output HCL instead of JSON

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_Layout.cshtml, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_NotificationBanner.cshtml, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/appsettings.json
Based on the work completed for Recast https://github.com/DFE-Digital/record-concerns-support-trusts/pull/1210
I have added a notification component that is wrapped by a conditional statement.
If the message value is set to a string (either via appsettings or env var) then it will display the component.
This is useful for displaying upcoming maintenance windows or important critical information (such as notification of IT outage)
=> Display Notification Banner above site if message is set

Dockerfile.api, Dockerfile.web
Tracking the minor version ensures we can receive all upstream security patches from Microsoft such as for:
- CVE-2024-21392
- CVE-2024-21386
=> Pin to 8.0.x for upstream security updates

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Startup.cs
**What is the change?**
Set 'secure' flag on .AspNetCore.Antiforgery cookie
**Why do we need the change?**
All cookies set by the application must have httpOnly and secure flags set to adhere to recommended remediations in the 2024 ITHC.
**What is the impact?**
Will only take affect when existing cookies expire or are cleared
**Azure DevOps Ticket**
#171441 [ITHC] 6.1.6. Cookie misconfiguration
=> Set 'secure' flag on Anti Forgery cookie

.github/workflows/build-and-push-image.yml
* The condition ensures that when the api container deploys there is not an additional marker in app insights. We dont want this to happen because they are both deployed at the same time and share the same app insights instance
=> Annotate releases in App Insights for all environments

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/create-individual-project.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-overview.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-tasks-completed-count.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/smoke/smoke-create-individual-project-to-check-answers-page.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/Getting-ready-to-open/applications-evidence.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/tasks/setting-up/Tasklist-School.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/createProject/createProjectPage.ts
This PR fixes few cypress tests which were failing due to the recent change done for **Residential or boarding provision** 
Updated the tests according to the new change
=> Fixed and updated cypress tests

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/api/domain.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/api/requestBuilder.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/homepage.cy.ts, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/projectRow.ts
Include project type in homepage test to make sure it's displaying on the Project list page.
=> Include project type in homepage tests

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/pages/taskListPage.ts
Missed to push this change . It should fix the ROM test
=> Readiness to Open meeting test fix

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.CypressTests/cypress/e2e/project-tasks-completed-count.cy.ts
This PR fixes  project-tasks-completed-count test
=> Updated correct count

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Dfe.ManageFreeSchoolProjects.API.csproj, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/Startup.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.API/StartupConfiguration/DatabaseConfigurationExtensions.cs, Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Startup.cs
This will ensure that the healthcheck endpoint correctly reports the status of the service if a database connection faults
=> Add DbContextChecks to Health Checks

.github/workflows/cypress-tests.yml
- These changes update the Cypress GitHub Workflow so that it will use the official Cypress GitHub Action for executing Cypress Tests. This will enable us to make use of caching, and standardises the approach across all of the other RSD services.
- I have also enabled the workflow_dispatch trigger so that Cypress tests can be run manually against a target environment
- Using a 'matrix' strategy will also enable us to test against multiple browsers in the future if we decide to do so
=> Use Cypress.io GitHub Action

.github/workflows/build-and-push-image.yml
- This change ensures that both the web and api images get built, imported and restarted at the same time.
- Build and import tasks run in parallel
- The workflow is easier to manipulate at different stages
=> Split workflow into concurrent build and import stages

Dockerfile.api, script/sqlcmd-docker-entrypoint.sh
- The RHEL repo that we download from Microsoft was formatted incorrectly for use in Azure Linux (which is RHEL 8 compatible) so we have to do a bit of correction before we can install packages from it
=> Fix gpg validation issue with mssql-tools

nuget.config
Adding `nuget.config` to allow GitHub Actions/Renovate CLI to read from the remote DFE nuget feed.
=> Added nuget config

release-notes.md
This release includes the following change: 
Add 'Voluntary Aided' school type option for Presumption and Central route projects.
=> Release1.0.2 for VA school type

.github/workflows/continuous-integration-dotnet.yml
This forms part of the work to make Sonarqube a mandatory quality gate.
Introducing the `sonar.qualitygate.wait=true` parameter ensures that the scanner will wait for the report to be generated and will fail the workflow if the gate is red, rather than completing the workflow regardless of the gate
=> Wait for quality gate response from Sonar before finishing the workflow

Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects/Pages/Shared/_LayoutNoHeaderAndFooter.cshtml
Ensure the maintenance banner appears on pages that do not use the default header layout
=> Include NotificationBanner on NoHeaderAndFooter Layout

.github/workflows/build-and-push-image.yml
Package validator commit hash has been updated to pick up the new policy
=> Package Validator policy update
